'use client';
import { createContext, useContext, useState, useCallback } from 'react';

const translations = {
  en: {
    brand: 'MedExpress',
    tagline: 'Your Trusted Medicine Delivery Partner',
    heroTitle: 'Order Medicines from Lucknow',
    heroSubtitle: 'Delivered Right to Your Doorstep',
    heroDesc: 'No more traveling 200-300 km for medicines. Upload your prescription and get genuine medicines delivered to Domariyaganj and nearby areas.',
    uploadPrescription: 'Upload Prescription',
    orderWhatsApp: 'Order via WhatsApp',
    trackOrder: 'Track Order',
    home: 'Home',
    upload: 'Upload Prescription',
    track: 'Track Order',
    contact: 'Contact',
    admin: 'Admin',
    howItWorks: 'How It Works',
    step1Title: 'Upload Prescription',
    step1Desc: 'Take a photo of your prescription and upload it through our simple form or WhatsApp.',
    step2Title: 'We Process & Purchase',
    step2Desc: 'Our team verifies your prescription and purchases medicines from trusted Lucknow pharmacies.',
    step3Title: 'Delivered to Your Door',
    step3Desc: 'Receive your medicines at home with transparent pricing and safe packaging.',
    serviceHighlights: 'Why Choose MedExpress?',
    genuineMeds: 'Genuine Medicines',
    genuineMedsDesc: '100% authentic medicines sourced only from licensed, trusted pharmacies in Lucknow.',
    fastDelivery: 'Fast Delivery',
    fastDeliveryDesc: 'Quick and reliable delivery to Domariyaganj and nearby towns within 2-3 business days.',
    trustedPartners: 'Trusted Partner Pharmacies',
    trustedPartnersDesc: 'We partner with reputed pharmacies to ensure quality and authenticity of every medicine.',
    affordablePricing: 'Affordable Pricing',
    affordablePricingDesc: 'Medicine at MRP with a small transparent delivery fee. No hidden charges.',
    testimonials: 'What Our Customers Say',
    faq: 'Frequently Asked Questions',
    faq1Q: 'How do I place an order?',
    faq1A: 'Simply upload your prescription on our website or send it via WhatsApp. Our team will verify it and deliver the medicines to your address.',
    faq2Q: 'What areas do you deliver to?',
    faq2A: 'We currently deliver to Domariyaganj, Basti, Khalilabad, and nearby towns in Uttar Pradesh.',
    faq3Q: 'How long does delivery take?',
    faq3A: 'Typically 2-3 business days from the time your order is confirmed.',
    faq4Q: 'Is a prescription mandatory?',
    faq4A: 'Yes, we only deliver medicines against valid prescriptions from a registered medical practitioner.',
    faq5Q: 'What payment methods do you accept?',
    faq5A: 'We accept UPI payments, online payment via Razorpay, and Cash on Delivery.',
    faq6Q: 'Are the medicines genuine?',
    faq6A: 'Absolutely. All medicines are purchased from licensed pharmacies in Lucknow with proper billing.',
    fullName: 'Full Name',
    mobileNumber: 'Mobile Number',
    completeAddress: 'Complete Address',
    uploadPrescriptionImage: 'Upload Prescription Image',
    dragDrop: 'Drag & drop your prescription here or click to browse',
    supportedFormats: 'Supported formats: JPG, PNG, PDF (Max 10MB)',
    medicineNotes: 'Medicine Notes (Optional)',
    medicineNotesPlaceholder: 'Any specific notes about medicines or substitutes...',
    preferredDeliveryTime: 'Preferred Delivery Time',
    morning: 'Morning (9 AM - 12 PM)',
    afternoon: 'Afternoon (12 PM - 4 PM)',
    evening: 'Evening (4 PM - 8 PM)',
    anytime: 'Anytime',
    monthlySubscription: 'Monthly Subscription (Repeat Medicines)',
    subscriptionDesc: 'Enable auto-refill for regular medicines (BP, Diabetes, etc.)',
    submitOrder: 'Submit Order',
    submitting: 'Submitting...',
    orderConfirmed: 'Order Confirmed!',
    orderConfirmedMsg: 'Your order has been received. We will verify your prescription and contact you shortly.',
    yourOrderId: 'Your Order ID',
    trackYourOrder: 'Track Your Order',
    orderTracking: 'Order Tracking',
    enterMobileOrOrder: 'Enter your mobile number or Order ID to track your order',
    mobileOrOrderId: 'Mobile Number or Order ID',
    search: 'Search',
    searching: 'Searching...',
    orderStatus: 'Order Status',
    received: 'Received',
    processing: 'Processing',
    purchased: 'Purchased',
    outForDelivery: 'Out for Delivery',
    delivered: 'Delivered',
    orderId: 'Order ID',
    customerName: 'Customer Name',
    orderDate: 'Order Date',
    noOrderFound: 'No order found. Please check your mobile number or Order ID.',
    contactUs: 'Contact & Support',
    contactDesc: 'We are here to help you. Reach out to us anytime.',
    whatsappChat: 'Chat on WhatsApp',
    callUs: 'Call Us',
    emailUs: 'Email Us',
    businessHours: 'Business Hours',
    monSat: 'Monday - Saturday',
    sunday: 'Sunday',
    closed: 'Closed',
    serviceArea: 'Our Service Area',
    getInTouch: 'Get In Touch',
    yourName: 'Your Name',
    yourEmail: 'Your Email',
    yourMessage: 'Your Message',
    sendMessage: 'Send Message',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    disclaimer: 'We deliver medicines only against valid prescriptions. We do not sell restricted medicines without verification.',
    allRightsReserved: 'All rights reserved.',
    quickLinks: 'Quick Links',
    legal: 'Legal',
    contactInfo: 'Contact Info',
    adminLogin: 'Admin Login',
    password: 'Password',
    login: 'Login',
    loggingIn: 'Logging in...',
    dashboard: 'Orders Dashboard',
    logout: 'Logout',
    actions: 'Actions',
    updateStatus: 'Update Status',
    downloadRx: 'Download Rx',
    whatsapp: 'WhatsApp',
    allOrders: 'All Orders',
    filterByStatus: 'Filter by Status',
    all: 'All',
    noOrders: 'No orders found.',
    payment: 'Payment',
    orderSummary: 'Order Summary',
    medicineCost: 'Medicine Cost (at MRP)',
    deliveryFee: 'Delivery Fee',
    total: 'Total',
    payWithRazorpay: 'Pay with Razorpay',
    payWithUPI: 'Pay with UPI',
    cashOnDelivery: 'Cash on Delivery',
    selectPayment: 'Select Payment Method',
    codConfirmed: 'Cash on Delivery confirmed! You will pay when you receive your medicines.',
    stats: 'Trusted by Families Across Eastern UP',
    ordersDelivered: 'Orders Delivered',
    happyCustomers: 'Happy Customers',
    partnerPharmacies: 'Partner Pharmacies',
    townsServed: 'Towns Served',
    address: 'Address',
    notes: 'Notes',
    subscription: 'Subscription',
    deliveryTime: 'Delivery Time',
    prescription: 'Prescription',
    viewPrescription: 'View Prescription',
  },
  hi: {
    brand: 'MedExpress',
    tagline: 'आपका विश्वसनीय दवा डिलीवरी पार्टनर',
    heroTitle: 'लखनऊ से दवाइयाँ मंगवाएँ',
    heroSubtitle: 'सीधे आपके घर तक पहुँचाई जाएँगी',
    heroDesc: 'दवाइयों के लिए 200-300 किमी सफ़र की ज़रूरत नहीं। अपना प्रिस्क्रिप्शन अपलोड करें और डोमरियागंज व आसपास के क्षेत्रों में असली दवाइयाँ पाएँ।',
    uploadPrescription: 'प्रिस्क्रिप्शन अपलोड करें',
    orderWhatsApp: 'WhatsApp से ऑर्डर करें',
    trackOrder: 'ऑर्डर ट्रैक करें',
    home: 'होम',
    upload: 'प्रिस्क्रिप्शन अपलोड',
    track: 'ऑर्डर ट्रैक',
    contact: 'संपर्क',
    admin: 'एडमिन',
    howItWorks: 'कैसे काम करता है',
    step1Title: 'प्रिस्क्रिप्शन अपलोड करें',
    step1Desc: 'अपने प्रिस्क्रिप्शन की फोटो लें और हमारे फॉर्म या WhatsApp के ज़रिए अपलोड करें।',
    step2Title: 'हम प्रोसेस और खरीद करते हैं',
    step2Desc: 'हमारी टीम आपके प्रिस्क्रिप्शन की जाँच करती है और लखनऊ की विश्वसनीय फार्मेसियों से दवाइयाँ खरीदती है।',
    step3Title: 'आपके दरवाज़े तक डिलीवरी',
    step3Desc: 'पारदर्शी मूल्य और सुरक्षित पैकेजिंग के साथ अपनी दवाइयाँ घर पर प्राप्त करें।',
    serviceHighlights: 'MedExpress क्यों चुनें?',
    genuineMeds: 'असली दवाइयाँ',
    genuineMedsDesc: 'लखनऊ की लाइसेंस प्राप्त, विश्वसनीय फार्मेसियों से 100% प्रामाणिक दवाइयाँ।',
    fastDelivery: 'तेज़ डिलीवरी',
    fastDeliveryDesc: 'डोमरियागंज और आसपास के शहरों में 2-3 कार्य दिवसों में तेज़ और विश्वसनीय डिलीवरी।',
    trustedPartners: 'विश्वसनीय पार्टनर फार्मेसी',
    trustedPartnersDesc: 'हम प्रतिष्ठित फार्मेसियों के साथ साझेदारी करते हैं ताकि हर दवा की गुणवत्ता सुनिश्चित हो।',
    affordablePricing: 'किफ़ायती मूल्य',
    affordablePricingDesc: 'MRP पर दवाइयाँ, छोटी पारदर्शी डिलीवरी फीस। कोई छुपे शुल्क नहीं।',
    testimonials: 'हमारे ग्राहक क्या कहते हैं',
    faq: 'अक्सर पूछे जाने वाले प्रश्न',
    faq1Q: 'मैं ऑर्डर कैसे दूँ?',
    faq1A: 'बस हमारी वेबसाइट पर अपना प्रिस्क्रिप्शन अपलोड करें या WhatsApp पर भेजें। हमारी टीम इसकी जाँच करेगी और दवाइयाँ आपके पते पर पहुँचाएगी।',
    faq2Q: 'आप कहाँ-कहाँ डिलीवरी करते हैं?',
    faq2A: 'हम वर्तमान में डोमरियागंज, बस्ती, खलीलाबाद और उत्तर प्रदेश के आसपास के शहरों में डिलीवरी करते हैं।',
    faq3Q: 'डिलीवरी में कितना समय लगता है?',
    faq3A: 'आमतौर पर ऑर्डर कन्फर्म होने से 2-3 कार्य दिवसों के अंदर।',
    faq4Q: 'क्या प्रिस्क्रिप्शन ज़रूरी है?',
    faq4A: 'हाँ, हम केवल पंजीकृत चिकित्सक के वैध प्रिस्क्रिप्शन पर ही दवाइयाँ भेजते हैं।',
    faq5Q: 'आप कौन से भुगतान तरीके स्वीकार करते हैं?',
    faq5A: 'हम UPI, Razorpay के ज़रिए ऑनलाइन भुगतान और कैश ऑन डिलीवरी स्वीकार करते हैं।',
    faq6Q: 'क्या दवाइयाँ असली हैं?',
    faq6A: 'बिल्कुल। सभी दवाइयाँ लखनऊ की लाइसेंस प्राप्त फार्मेसियों से उचित बिलिंग के साथ खरीदी जाती हैं।',
    fullName: 'पूरा नाम',
    mobileNumber: 'मोबाइल नंबर',
    completeAddress: 'पूरा पता',
    uploadPrescriptionImage: 'प्रिस्क्रिप्शन इमेज अपलोड करें',
    dragDrop: 'यहाँ प्रिस्क्रिप्शन ड्रैग और ड्रॉप करें या ब्राउज़ करें',
    supportedFormats: 'सपोर्टेड फॉर्मेट: JPG, PNG, PDF (अधिकतम 10MB)',
    medicineNotes: 'दवा नोट्स (वैकल्पिक)',
    medicineNotesPlaceholder: 'दवाइयों या विकल्पों के बारे में कोई विशेष नोट...',
    preferredDeliveryTime: 'पसंदीदा डिलीवरी समय',
    morning: 'सुबह (9 AM - 12 PM)',
    afternoon: 'दोपहर (12 PM - 4 PM)',
    evening: 'शाम (4 PM - 8 PM)',
    anytime: 'कभी भी',
    monthlySubscription: 'मासिक सब्सक्रिप्शन (नियमित दवाइयाँ)',
    subscriptionDesc: 'नियमित दवाइयों (BP, डायबिटीज़, आदि) के लिए ऑटो-रिफिल चालू करें',
    submitOrder: 'ऑर्डर सबमिट करें',
    submitting: 'सबमिट हो रहा है...',
    orderConfirmed: 'ऑर्डर कन्फर्म!',
    orderConfirmedMsg: 'आपका ऑर्डर प्राप्त हो गया है। हम आपके प्रिस्क्रिप्शन की जाँच कर आपसे जल्द संपर्क करेंगे।',
    yourOrderId: 'आपका ऑर्डर ID',
    trackYourOrder: 'अपना ऑर्डर ट्रैक करें',
    orderTracking: 'ऑर्डर ट्रैकिंग',
    enterMobileOrOrder: 'अपना मोबाइल नंबर या ऑर्डर ID डालें',
    mobileOrOrderId: 'मोबाइल नंबर या ऑर्डर ID',
    search: 'खोजें',
    searching: 'खोज रहा है...',
    orderStatus: 'ऑर्डर स्टेटस',
    received: 'प्राप्त',
    processing: 'प्रोसेसिंग',
    purchased: 'खरीदा गया',
    outForDelivery: 'डिलीवरी के लिए निकला',
    delivered: 'डिलीवर हो गया',
    orderId: 'ऑर्डर ID',
    customerName: 'ग्राहक का नाम',
    orderDate: 'ऑर्डर तारीख',
    noOrderFound: 'कोई ऑर्डर नहीं मिला। कृपया अपना मोबाइल नंबर या ऑर्डर ID जाँचें।',
    contactUs: 'संपर्क और सहायता',
    contactDesc: 'हम आपकी मदद के लिए यहाँ हैं। कभी भी संपर्क करें।',
    whatsappChat: 'WhatsApp पर चैट करें',
    callUs: 'कॉल करें',
    emailUs: 'ईमेल करें',
    businessHours: 'व्यापार के घंटे',
    monSat: 'सोमवार - शनिवार',
    sunday: 'रविवार',
    closed: 'बंद',
    serviceArea: 'हमारा सेवा क्षेत्र',
    getInTouch: 'संपर्क करें',
    yourName: 'आपका नाम',
    yourEmail: 'आपका ईमेल',
    yourMessage: 'आपका संदेश',
    sendMessage: 'संदेश भेजें',
    privacyPolicy: 'गोपनीयता नीति',
    termsOfService: 'सेवा शर्तें',
    disclaimer: 'हम केवल वैध प्रिस्क्रिप्शन पर ही दवाइयाँ भेजते हैं। बिना सत्यापन के प्रतिबंधित दवाइयाँ नहीं बेचते।',
    allRightsReserved: 'सर्वाधिकार सुरक्षित।',
    quickLinks: 'त्वरित लिंक',
    legal: 'कानूनी',
    contactInfo: 'संपर्क जानकारी',
    adminLogin: 'एडमिन लॉगिन',
    password: 'पासवर्ड',
    login: 'लॉगिन',
    loggingIn: 'लॉगिन हो रहा है...',
    dashboard: 'ऑर्डर डैशबोर्ड',
    logout: 'लॉगआउट',
    actions: 'कार्रवाई',
    updateStatus: 'स्टेटस अपडेट',
    downloadRx: 'Rx डाउनलोड',
    whatsapp: 'WhatsApp',
    allOrders: 'सभी ऑर्डर',
    filterByStatus: 'स्टेटस से फ़िल्टर ',
    all: 'सभी',
    noOrders: 'कोई ऑर्डर नहीं मिला।',
    payment: 'भुगतान',
    orderSummary: 'ऑर्डर सारांश',
    medicineCost: 'दवा लागत (MRP पर)',
    deliveryFee: 'डिलीवरी शुल्क',
    total: 'कुल',
    payWithRazorpay: 'Razorpay से भुगतान',
    payWithUPI: 'UPI से भुगतान',
    cashOnDelivery: 'कैश ऑन डिलीवरी',
    selectPayment: 'भुगतान तरीका चुनें',
    codConfirmed: 'कैश ऑन डिलीवरी कन्फर्म! दवाइयाँ मिलने पर भुगतान करें।',
    stats: 'पूर्वी उत्तर प्रदेश के परिवारों का भरोसा',
    ordersDelivered: 'ऑर्डर डिलीवर हुए',
    happyCustomers: 'खुश ग्राहक',
    partnerPharmacies: 'पार्टनर फार्मेसी',
    townsServed: 'शहरों में सेवा',
    address: 'पता',
    notes: 'नोट्स',
    subscription: 'सब्सक्रिप्शन',
    deliveryTime: 'डिलीवरी समय',
    prescription: 'प्रिस्क्रिप्शन',
    viewPrescription: 'प्रिस्क्रिप्शन देखें',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('en');

  const t = useCallback((key) => {
    return translations[lang]?.[key] || translations.en[key] || key;
  }, [lang]);

  const toggleLanguage = useCallback(() => {
    setLang(prev => prev === 'en' ? 'hi' : 'en');
  }, []);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
